## Test Predictor class

In [1]:
from models import DistanceModel

Using TensorFlow backend.


In [4]:
model = DistanceModel(que_dim= 27 - 2 + 14 - 2,
                                  que_input_embs=[102, 42], que_output_embs=[2, 2],
                                  pro_dim=33 - 2,
                                  pro_input_embs=[102, 102, 42], pro_output_embs=[2, 2, 2],
                                  inter_dim=16, output_dim=10)
model.load_weights('dump/model.h5')

In [5]:
import importlib

In [6]:
import predictor

C:\Users\nikitosoleil\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [105]:
importlib.reload(predictor)

<module 'predictor' from 'C:\\Users\\nikitosoleil\\DataRoot\\cv\\cv\\proj\\predictor.py'>

In [106]:
pred = predictor.Predictor(model, 'dump/')

[100 10 23 -0.5560829897714368 0.4140303428843267 -3.3346738412898826
 0.43776379623592826 1.308695572124488 -2.1737440423302923
 1.1405994918381603 -0.5702975770724269 -0.11725153028964996
 -0.9851715564727783 0.252293199300766 -1.070906400680542
 -0.31238463521003723 -0.8020544648170471 0.11489026993513107
 0.01884876936674118 0.4159659147262573 0.8283409476280212
 1.0396236181259155 -0.4579142928123474 -0.7106772661209106
 -1.1589419841766357 -1.1437820196151733 -0.8788050413131714
 -1.1638669967651367 0.11068644374608994 -0.11706457287073135
 0.8814422488212585]
[100 10 23 -0.5560829897714368 0.4140303428843267 -3.3346738412898826
 0.43776379623592826 1.308695572124488 -2.1737440423302923
 1.1405994918381603 -0.5702975770724269 -0.11725153028964996
 -0.9851715564727783 0.252293199300766 -1.070906400680542
 -0.31238463521003723 -0.8020544648170471 0.11489026993513107
 0.01884876936674118 0.4159659147262573 0.8283409476280212
 1.0396236181259155 -0.4579142928123474 -0.710677266120910

In [30]:
que_dict = {
    'questions_id': ['332a511f1569444485cf7a7a556a5e54'],
    'questions_author_id': ['8f6f374ffd834d258ab69d376dd998f5'],
    'questions_date_added': ['2016-04-26 11:14:26'],
    'questions_title': ['Teacher   career   question'],
    'questions_body': ['What  is  a  maths  teacher?   what  is  a  maths  teacher  useful? #college #professor #lecture'],
    'questions_tags': ['college professor lecture']
}

In [31]:
que_df, que_tags = pred.convert_que_dict(que_dict)

### Recommend the question to professionals

In [32]:
pred.find_pros_by_que(que_df, que_tags)

id                            match_id  \
0  332a511f1569444485cf7a7a556a5e54  [f64df9b489864952917cb631be1ddac7]   
1  332a511f1569444485cf7a7a556a5e54  [eae832d70c5246f7b8e4064a271b9631]   
2  332a511f1569444485cf7a7a556a5e54  [fb2d8790e1b548ae87767251006bf0a4]   
3  332a511f1569444485cf7a7a556a5e54  [408c588903de4afd9f2a3120b713d732]   
4  332a511f1569444485cf7a7a556a5e54  [3a03b74d6d0b40219d842e95622a91be]   
5  332a511f1569444485cf7a7a556a5e54  [4dc7d9040592416f98c0bef1ad2c31f5]   
6  332a511f1569444485cf7a7a556a5e54  [16ff670578744fee9c135dd03f7eaff5]   
7  332a511f1569444485cf7a7a556a5e54  [0bb33e7087204d11a571c0c9190e1c6b]   
8  332a511f1569444485cf7a7a556a5e54  [df0326aca38f4fdfb7613251af52587b]   
9  332a511f1569444485cf7a7a556a5e54  [afee49299b50481e9902289beca5b685]   

   match_score  
0     0.878095  
1     0.872991  
2     0.848396  
3     0.842452  
4     0.839536  
5     0.834179  
6     0.830868  
7     0.830506  
8     0.830316  
9     0.829512

### Find similar questions

In [33]:
pred.find_ques_by_que(que_df, que_tags)

id                            match_id  \
0  332a511f1569444485cf7a7a556a5e54  [332a511f1569444485cf7a7a556a5e54]   
1  332a511f1569444485cf7a7a556a5e54  [cb77402ea78f43239add0eacc2806ddf]   
2  332a511f1569444485cf7a7a556a5e54  [85ff7763be774769a95f2b61264d0290]   
3  332a511f1569444485cf7a7a556a5e54  [cf0fa55997da4bd4a8fc59da8a30c65c]   
4  332a511f1569444485cf7a7a556a5e54  [e7d2060951e5479bbbe667e725b65d13]   
5  332a511f1569444485cf7a7a556a5e54  [776900824fde4202b0388c0b793444eb]   
6  332a511f1569444485cf7a7a556a5e54  [86588f216d754aa78c27016504cee074]   
7  332a511f1569444485cf7a7a556a5e54  [ef8f38111292438e8baf3760f89206ed]   
8  332a511f1569444485cf7a7a556a5e54  [23e0f09073e94e248059ef8419dbf2c7]   
9  332a511f1569444485cf7a7a556a5e54  [e97182f64db84841a7d7f9ce840b4de0]   

   match_score  
0     0.991790  
1     0.938819  
2     0.937305  
3     0.930767  
4     0.924923  
5     0.918333  
6     0.913436  
7     0.912007  
8     0.911176  
9     0.909651

In [11]:
np.arange(0, pred.que_ids.shape[0]).reshape(-1, 1)[pred.que_ids == '332a511f1569444485cf7a7a556a5e54']

array([356])

In [14]:
pred.que_lat_vecs[356, :]

array([-0.16272298, -0.37503865,  0.155104  ,  0.1808311 ,  0.16123109,
       -0.2178492 , -0.41472468,  0.14317678, -0.02055809, -0.18998995],
      dtype=float32)

In [15]:
pred.que_feat[356, :]

array([14, 10, -0.22259948167676602, -0.5578865162861019,
       -0.4425965550060855, -0.06277095584967236, -0.6340867716159001,
       -0.3775441067623759, -0.3598273694515228, -0.6401242613792419,
       -0.1037975326180458, -0.7375578284263611, -0.7670846581459045,
       -0.730384886264801, 0.3594370186328888, 0.5902867317199707,
       0.20080788433551788, 0.8254199028015137, 0.652858316898346,
       -0.5015465617179871, 0.021854806691408157, 0.40655016899108887,
       -0.5136355757713318, -0.042927633970975876, -0.2778507471084595,
       0.03534337133169174, 0.578580915927887, 0.3535146713256836],
      dtype=object)

---

In [46]:
pro_dict = {
    'professionals_id': ['44b2484ecd3642c6a47514f3876cf14a'],
    'professionals_location': ['Cambridge, Massachusetts'],
    'professionals_industry': ['Healthcare, Pharmaceuticals, Life Science'],
    'professionals_headline': ['Scientist and Healthcare Entrepreneur'],
    'professionals_date_joined': ['2012-01-25 20:40:43'],
    'professionals_subscribed_tags': ['pharmaceutical-industry medicine healthcare-it biology science healthcare research']
}

In [47]:
pro_df, pro_tags = predictor.Predictor.convert_pro_dict(pro_dict)

### Recommend questions to the professional

In [37]:
import pandas as pd

In [48]:
ans_df = pd.read_csv('../../data/answers.csv')
que_df = pd.read_csv('../../data/questions.csv')

In [84]:
pred.find_ques_by_pro(pro_df, que_df, ans_df, pro_tags)

[[100 10 23 -0.5560829897714368 0.4140303428843267 -3.3346738412898826
  0.43776379623592826 1.308695572124488 -0.6637406984602068
  0.3097139032095262 0.9863223311285867 -0.11725153028964996
  -0.9851716160774231 0.2522932291030884 -1.070906400680542
  -0.31238463521003723 -0.8020545244216919 0.11489026993513107
  0.018848776817321777 0.4159659445285797 0.8283408880233765
  1.0396236181259155 -0.4579142928123474 -0.7106772661209106
  -1.1589419841766357 -1.1437820196151733 -0.8788050413131714
  -1.1638669967651367 0.11068644374608994 -0.11706457287073135
  0.8814422488212585]]


id                            match_id  \
0  44b2484ecd3642c6a47514f3876cf14a  [d5822443bad84a7092e805fb1629f769]   
1  44b2484ecd3642c6a47514f3876cf14a  [f0f74e63b05a4ad7b8a92e6e108ae545]   
2  44b2484ecd3642c6a47514f3876cf14a  [319c16e889cf4198b508935b3294f2e9]   
3  44b2484ecd3642c6a47514f3876cf14a  [89f7581ca5fd4e7885184d1fa0f4e6dd]   
4  44b2484ecd3642c6a47514f3876cf14a  [bfab77ba3de24e5784fe764558b6ea7b]   
5  44b2484ecd3642c6a47514f3876cf14a  [4c66ee5a680e45bf9c7ce8b30fdbb6da]   
6  44b2484ecd3642c6a47514f3876cf14a  [f922046b741344c095534c01602c0aea]   
7  44b2484ecd3642c6a47514f3876cf14a  [040f9c98fa5a49c98f54a91bc082b65d]   
8  44b2484ecd3642c6a47514f3876cf14a  [e46d0678611c48a18774eddd75cea3b6]   
9  44b2484ecd3642c6a47514f3876cf14a  [45ce5b52ceda4469b53277c02ba1497e]   

   match_score  
0     0.798401  
1     0.763545  
2     0.761038  
3     0.760006  
4     0.750374  
5     0.747826  
6     0.745425  
7     0.740921  
8     0.738813  
9     0.733469

In [107]:
s = pred.find_pros_by_pro(pro_df, que_df, ans_df, pro_tags, 10000)

[[100 10 23 -0.5560829897714368 0.4140303428843267 -3.3346738412898826
  0.43776379623592826 1.308695572124488 -0.6637406984602068
  0.3097139032095262 0.9863223311285867 -0.11725153028964996
  -0.9851716160774231 0.2522932291030884 -1.070906400680542
  -0.31238463521003723 -0.8020545244216919 0.11489026993513107
  0.018848776817321777 0.4159659445285797 0.8283408880233765
  1.0396236181259155 -0.4579142928123474 -0.7106772661209106
  -1.1589419841766357 -1.1437820196151733 -0.8788050413131714
  -1.1638669967651367 0.11068644374608994 -0.11706457287073135
  0.8814422488212585]]
[[ 0.09889327  0.02275338  0.04679578  0.02456458 -0.3907954   0.20065689
   0.4277932  -0.65781915  0.11931917  0.01335122]]


In [98]:
s

id                            match_id  \
0     44b2484ecd3642c6a47514f3876cf14a  [e3a8860444b04d3485d678388ba675be]   
1     44b2484ecd3642c6a47514f3876cf14a  [0166e174028843dca3a392053f9732c8]   
2     44b2484ecd3642c6a47514f3876cf14a  [77a65aed859f4b11983cd07399f1e3b1]   
3     44b2484ecd3642c6a47514f3876cf14a  [d42114db82844f2b8f2c79664b770c10]   
4     44b2484ecd3642c6a47514f3876cf14a  [17931d09114940d4a23d7f88af20dd59]   
5     44b2484ecd3642c6a47514f3876cf14a  [96a3880b926d49fab0a4bc17994580a2]   
6     44b2484ecd3642c6a47514f3876cf14a  [5c6bc970b7ef482da7efa9a33907a234]   
7     44b2484ecd3642c6a47514f3876cf14a  [40d2a3407dab4c819afa0c51fbf284ac]   
8     44b2484ecd3642c6a47514f3876cf14a  [1a49821dcc314d9f93f3e6711f7a3cd7]   
9     44b2484ecd3642c6a47514f3876cf14a  [62fe681dfa8844ae94a6bdb10aef27cc]   
10    44b2484ecd3642c6a47514f3876cf14a  [c39329e6c790449f812590c3b897aca8]   
11    44b2484ecd3642c6a47514f3876cf14a  [47359d7eb98441498631287976e94086]   
12    44b2484ecd3642c6a47514f3876cf14a  [8f48370932c443e19600787107bc6edc]   
13    44b2484ecd3642c6a47514f3876cf14a  [6f03318a272f460d8df27914cd6de1f1]   
14    44b2484ecd3642c6a47514f3876cf14a  [64fdb079c8bb499896c91874764b6910]   
15    44b2484ecd3642c6a47514f3876cf14a  [80b146f8b74847d58a34989970536511]   
16    44b2484ecd3642c6a47514f3876cf14a  [8725054cf9af45d280327217e851ab41]   
17    44b2484ecd3642c6a47514f3876cf14a  [8cb68357763f4e90a7537bffc9ac11ea]   
18    44b2484ecd3642c6a47514f3876cf14a  [a3ba3216d0c147a0a88c56bb34dff033]   
19    44b2484ecd3642c6a47514f3876cf14a  [b987ec3d01784103b6c32a7e8eb439f6]   
20    44b2484ecd3642c6a47514f3876cf14a  [11c049d0272d4fa28738ad33eb450f12]   
21    44b2484ecd3642c6a47514f3876cf14a  [428b3e58119c4f86b2cd628ceee8fbeb]   
22    44b2484ecd3642c6a47514f3876cf14a  [35342f32efeb432ba9f6d40512682bcd]   
23    44b2484ecd3642c6a47514f3876cf14a  [db79aeafba18418ca36b8695a6c4b34f]   
24    44b2484ecd3642c6a47514f3876cf14a  [cf9f6541d60b4f4798af43a429894e59]   
25    44b2484ecd3642c6a47514f3876cf14a  [16c13f8926a341b7ba5291b43b45b0eb]   
26    44b2484ecd3642c6a47514f3876cf14a  [2b37ae0a2587481482f0be9d7b8a9f26]   
27    44b2484ecd3642c6a47514f3876cf14a  [fc62f2d027214725ba683d62c242bc2b]   
28    44b2484ecd3642c6a47514f3876cf14a  [4e9b35234bdb4b02930ce248e29be3cd]   
29    44b2484ecd3642c6a47514f3876cf14a  [55f1595cc0a340d6abb4b73eed67f644]   
...                                ...                                 ...   
9970  44b2484ecd3642c6a47514f3876cf14a  [e773d6ccade64f38b1b960c6b64f0a2a]   
9971  44b2484ecd3642c6a47514f3876cf14a  [258cade180394e3c80559a75f5bd874b]   
9972  44b2484ecd3642c6a47514f3876cf14a  [209fcd55fefa4fe29ccedcdc26bd5d89]   
9973  44b2484ecd3642c6a47514f3876cf14a  [4ee8012894c944eb891b8887df51b3ec]   
9974  44b2484ecd3642c6a47514f3876cf14a  [e1321bada5224826a91d8cb7994888d0]   
9975  44b2484ecd3642c6a47514f3876cf14a  [cc0ef2b535894a77a92cc740be6c2513]   
9976  44b2484ecd3642c6a47514f3876cf14a  [603f8306af1a4707b35422e2fbb376d6]   
9977  44b2484ecd3642c6a47514f3876cf14a  [9800ccb6076042c3aa5d3b789e886c6c]   
9978  44b2484ecd3642c6a47514f3876cf14a  [13cbbcd3bb624a90803392348666913d]   
9979  44b2484ecd3642c6a47514f3876cf14a  [5cbd4a64a328414781df8b75e47ffad3]   
9980  44b2484ecd3642c6a47514f3876cf14a  [df478629d3604135b5f9b3af12c2bdc5]   
9981  44b2484ecd3642c6a47514f3876cf14a  [4593370bcdef483e99b23659a84d06c0]   
9982  44b2484ecd3642c6a47514f3876cf14a  [cf4019892cf24e2c8b4536570b46b7d1]   
9983  44b2484ecd3642c6a47514f3876cf14a  [b0376031d64e412c8517ecd1f3832284]   
9984  44b2484ecd3642c6a47514f3876cf14a  [eff34da33a0a4d6e8edb95430ac4ff0e]   
9985  44b2484ecd3642c6a47514f3876cf14a  [c021b1cc3a0c45b79a72fb04e2651d35]   
9986  44b2484ecd3642c6a47514f3876cf14a  [fd232e144cfd44eab38ee0017d2caafa]   
9987  44b2484ecd3642c6a47514f3876cf14a  [ba589b5df524433a93db2791eac3f991]   
9988  44b2484ecd3642c6a47514f3876cf14a  [59dbd43c917749c9ab96050639a0ea9a]   
9989  44b2484ecd3642c6a47514f3876cf14a  [62e29f2b1a9349159

In [104]:
s[s['match_id'] == '44b2484ecd3642c6a47514f3876cf14a']

id                            match_id  \
6517  44b2484ecd3642c6a47514f3876cf14a  [44b2484ecd3642c6a47514f3876cf14a]   

      match_score  
6517     0.241344

In [101]:
np.arange(0, pred.pro_ids.shape[0]).reshape(-1, 1)[pred.pro_ids == '44b2484ecd3642c6a47514f3876cf14a']

array([2637])

In [102]:
pred.pro_feat[2637]

array([100, 10, 23, -0.5560829897714368, 0.4140303428843267,
       -3.3346738412898826, 0.43776379623592826, 1.308695572124488,
       -2.1737440423302923, 1.1405994918381603, -0.5702975770724269,
       -0.11725153028964996, -0.9851715564727783, 0.252293199300766,
       -1.070906400680542, -0.31238463521003723, -0.8020544648170471,
       0.11489026993513107, 0.01884876936674118, 0.4159659147262573,
       0.8283409476280212, 1.0396236181259155, -0.4579142928123474,
       -0.7106772661209106, -1.1589419841766357, -1.1437820196151733,
       -0.8788050413131714, -1.1638669967651367, 0.11068644374608994,
       -0.11706457287073135, 0.8814422488212585], dtype=object)

In [103]:
pred.pro_lat_vecs[2637]

array([ 0.12160952,  0.03939573, -0.40439287, -0.01125311, -0.42210618,
        0.67033625, -0.04532274, -1.7624149 , -0.24541803,  0.14191574],
      dtype=float32)